/**
 * Core PetAI features — single source of truth used across all 20
 * theme layouts. Replaces the generic "Premium Services" /
 * "Concierge vet" placeholders with what PetAI actually does.
 *
 * Each feature has a route (where it lives in the app), an icon
 * (lucide-react component), and labels in EN/RU.
 */

import {
  Mic,         // bark analysis voice AI
  FlaskConical,// lab result vision
  Bot,         // AI chat assistant
  GraduationCap,// lifecycle upbringing
  Bell,        // reminders
  Stethoscope, // vet marketplace
  Heart,       // health score / wellness
  Activity,    // activity tracking
  Camera,      // photo upload / pet vision
  Pill,        // medications
  Calendar,    // schedule / vet visits
  ShoppingBag, // marketplace
  type LucideIcon,
} from "lucide-react";

export interface PetAiFeature {
  id: string;
  route: string;
  icon: LucideIcon;
  emoji: string;            // fallback for emoji-style layouts
  labelEn: string;
  labelRu: string;
  subEn: string;
  subRu: string;
  /** Brief tagline shown on cards in larger layouts. */
  taglineEn: string;
  taglineRu: string;
}

export const PET_AI_FEATURES: Record<string, PetAiFeature> = {
  bark: {
    id: "bark",
    route: "/collar",
    icon: Mic,
    emoji: "🎤",
    labelEn: "Bark AI",
    labelRu: "AI лая",
    subEn: "voice analysis",
    subRu: "анализ голоса",
    taglineEn: "Decode your dog's emotions from sound",
    taglineRu: "Расшифровка эмоций по голосу",
  },
  labs: {
    id: "labs",
    route: "/labs",
    icon: FlaskConical,
    emoji: "🧪",
    labelEn: "Lab Vision",
    labelRu: "Анализы AI",
    subEn: "decode bloodwork",
    subRu: "понять кровь",
    taglineEn: "AI explains lab results in plain English",
    taglineRu: "AI объяснит анализы простым языком",
  },
  chat: {
    id: "chat",
    route: "/assistant",
    icon: Bot,
    emoji: "🤖",
    labelEn: "AI Vet",
    labelRu: "AI ветеринар",
    subEn: "ask anything",
    subRu: "спроси что угодно",
    taglineEn: "Claude-powered pet health assistant",
    taglineRu: "AI ассистент здоровья от Claude",
  },
  upbringing: {
    id: "upbringing",
    route: "/upbringing",
    icon: GraduationCap,
    emoji: "🎓",
    labelEn: "Lifecycle",
    labelRu: "Воспитание",
    subEn: "age-by-age care",
    subRu: "уход по возрасту",
    taglineEn: "Care guidance for every life stage",
    taglineRu: "Гид по уходу по этапам жизни",
  },
  reminders: {
    id: "reminders",
    route: "/reminders",
    icon: Bell,
    emoji: "🔔",
    labelEn: "Reminders",
    labelRu: "Напоминания",
    subEn: "never miss a date",
    subRu: "не пропусти срок",
    taglineEn: "Auto-generated by age & breed",
    taglineRu: "Автоматически по возрасту и породе",
  },
  vets: {
    id: "vets",
    route: "/consultations",
    icon: Stethoscope,
    emoji: "🩺",
    labelEn: "Vet Network",
    labelRu: "Сеть ветов",
    subEn: "verified pros",
    subRu: "проверенные",
    taglineEn: "Book vets, trainers, breeders",
    taglineRu: "Запись к ветам, кинологам, заводчикам",
  },
  marketplace: {
    id: "marketplace",
    route: "/marketplace",
    icon: ShoppingBag,
    emoji: "🛍️",
    labelEn: "Marketplace",
    labelRu: "Маркетплейс",
    subEn: "puppies & gear",
    subRu: "щенки и товары",
    taglineEn: "Verified breeders & services",
    taglineRu: "Проверенные заводчики и услуги",
  },
  nutrition: {
    id: "nutrition",
    route: "/nutrition",
    icon: Heart,
    emoji: "🥗",
    labelEn: "Nutrition",
    labelRu: "Питание",
    subEn: "breed-specific",
    subRu: "по породе",
    taglineEn: "Diet tuned to breed and age",
    taglineRu: "Рацион по породе и возрасту",
  },
};

/** Most common 2-tile combinations used in compact layouts. */
export const FEATURE_PAIRS = {
  primary: ["bark", "labs"] as const,
  daily: ["reminders", "upbringing"] as const,
  social: ["vets", "marketplace"] as const,
};

/** Top 4 features for tiled / grid layouts. */
export const TOP_FEATURES = ["bark", "labs", "chat", "upbringing"] as const;

/** All 6 main features for "bento" layouts. */
export const HERO_FEATURES = ["bark", "labs", "chat", "upbringing", "reminders", "vets"] as const;
